### ISSUE TITLE
心跳全部失败

### ISSUE THREAD

**Issue by shaojintian** [kasvith/simplelb#2]
![image](https://user-images.githubusercontent.com/40530183/69806831-c87a5280-121e-11ea-8183-8b45f516747a.png)

**Comment by shaojintian** [comment]
go run main.go --backends=http://localhost:8081,http://localhost:8082,http://localhost:8083,http://localhost:8084
output:
2019/11/28 20:36:02 Configured server: http://localhost:8081
2019/11/28 20:36:02 Configured server: http://localhost:8082
2019/11/28 20:36:02 Configured server: http://localhost:8083
2019/11/28 20:36:02 Configured server: http://localhost:8084
2019/11/28 20:36:02 Load Balancer started at :3030
2019/11/28 20:36:22 Starting health check...
2019/11/28 20:36:22 Site unreachable, error:  dial tcp [::1]:8081: connect: connection refused
2019/11/28 20:36:22 http://localhost:8081 [down]
2019/11/28 20:36:22 Site unreachable, error:  dial tcp [::1]:8082: connect: connection refused
2019/11/28 20:36:22 http://localhost:8082 [down]
2019/11/28 20:36:22 Site unreachable, error:  dial tcp [::1]:8083: connect: connection refused
2019/11/28 20:36:22 http://localhost:8083 [down]
2019/11/28 20:36:22 Site unreachable, error:  dial tcp [::1]:8084: connect: connection refused
2019/11/28 20:36:22 http://localhost:8084 [down]
2019/11/28 20:36:22 Health check completed

**Comment by shaojintian** [comment]
我直接运行的，怎么打开backend的监听啊

**Comment by kasvith** [comment]
You need to start 4 backend servers you like in 8081, 8082, 8083, 8084
