### ISSUE TITLE
Question: Why time.After instead of time.Sleep ?

### ISSUE THREAD

**Issue by dev-drprasad** [kasvith/simplelb#4]
I learned lot from your article on load balancer. I see you used `select` with `time.After` to retry

https://github.com/kasvith/simplelb/blob/fd45a989dac5a9441f0bdf17c523b901799cc477/main.go#L185-L192

Why not just use `time.Sleep` ? Is there any difference between `time.Sleep` and `select` with `time.After` ?

**Comment by kasvith** [comment]
Main purpose to add `time.After` to have a flexible structure to run other concurrent tasks in the error handler.

It's ok to use time.Sleep as well, in that case, we cant interrupt it
